/**
 * Source File Editor - Read-only code viewer with edit capability warning
 */

import React, { useState } from 'react';
import {
  Box,
  Typography,
  Alert,
  AlertTitle,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  DialogContentText,
} from '@mui/material';
import { Lock as LockIcon, Edit as EditIcon } from '@mui/icons-material';

interface SourceFileEditorProps {
  filePath: string;
  content: string;
  onEnableEdit?: (filePath: string) => void;
}

const SourceFileEditor: React.FC<SourceFileEditorProps> = ({
  filePath,
  content,
  onEnableEdit,
}) => {
  const [isReadOnly, setIsReadOnly] = useState(true);
  const [showWarningDialog, setShowWarningDialog] = useState(false);

  const handleEnableEdit = () => {
    setShowWarningDialog(true);
  };

  const confirmEnableEdit = () => {
    setIsReadOnly(false);
    setShowWarningDialog(false);
    if (onEnableEdit) {
      onEnableEdit(filePath);
    }
  };

  return (
    <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      {/* File Header */}
      <Box
        sx={{
          p: 1.5,
          borderBottom: 1,
          borderColor: 'divider',
          bgcolor: 'background.default',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        }}
      >
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <LockIcon sx={{ fontSize: 18, opacity: isReadOnly ? 0.7 : 0.3 }} />
          <Typography variant="caption" sx={{ fontFamily: 'monospace', opacity: 0.7 }}>
            {filePath}
          </Typography>
        </Box>
        {isReadOnly && (
          <Button
            size="small"
            startIcon={<EditIcon />}
            onClick={handleEnableEdit}
            variant="outlined"
          >
            Enable Editing
          </Button>
        )}
      </Box>

      {/* Warning Alert */}
      {isReadOnly && (
        <Alert severity="info" sx={{ m: 2, mb: 0 }}>
          <AlertTitle>Read-Only Mode</AlertTitle>
          This file is auto-generated by SoupModMaker. Changes made through the visual
          editors will update this file automatically. Click "Enable Editing" to make
          manual changes (this will disable auto-generation until a future release).
        </Alert>
      )}

      {/* Code Editor */}
      <Box
        component="pre"
        contentEditable={!isReadOnly}
        suppressContentEditableWarning
        sx={{
          flex: 1,
          m: 0,
          p: 2,
          overflow: 'auto',
          bgcolor: 'grey.900',
          color: 'grey.100',
          fontSize: '0.813rem',
          fontFamily: 'monospace',
          lineHeight: 1.5,
          outline: 'none',
          opacity: isReadOnly ? 0.9 : 1,
          cursor: isReadOnly ? 'default' : 'text',
          '&:focus': {
            bgcolor: isReadOnly ? 'grey.900' : 'grey.800',
          },
        }}
      >
        {content}
      </Box>

      {/* Warning Dialog */}
      <Dialog
        open={showWarningDialog}
        onClose={() => setShowWarningDialog(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>Enable Manual Editing?</DialogTitle>
        <DialogContent>
          <DialogContentText>
            <strong>Warning:</strong> Once you enable manual editing for this file,
            SoupModMaker will no longer automatically update it when you make changes
            through the visual editors.
          </DialogContentText>
          <DialogContentText sx={{ mt: 2 }}>
            This limitation will be removed in a future release where we can
            intelligently merge your manual changes with auto-generated updates.
          </DialogContentText>
          <DialogContentText sx={{ mt: 2 }}>
            <strong>Are you sure you want to proceed?</strong>
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShowWarningDialog(false)}>Cancel</Button>
          <Button onClick={confirmEnableEdit} variant="contained" color="warning">
            Enable Editing
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default SourceFileEditor;
